version: "3.8"

services:
  reu_qa:
    build: .
    container_name: reu_qa_service
    ports:
      - "8000:8000"  # FastAPI API
      - "8501:8501"  # Streamlit UI
    env_file:
      - .env
    volumes:
      - .:/app  # Монтируем проект внутрь контейнера